// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdsdswakdzpdhyhmsxqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkc2Rzd2FrZHpwZGh5aG1zeHFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3NDgzMTgsImV4cCI6MjA4NTMyNDMxOH0.y9_pItCA2_Ao8irTrwSFbVmodoaH1sOtikDHP6csPmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});